#+latex_class: cn-article
#+title: Android Software Engineer Development 安卓程序员练成记
#+author: deepwaterooo: for Current LucidCarSettings

* Good to see all the changes during these year......

* Emacs
- Emacs has been my favoriate editor, and I am so dependent on it during my daily life that once it has some bug now, I don't hesitate to try to fix it as soon as possible. 
- https://github.com/deepwaterooo/emacs
- I began to use Emacs since Aug 2012, began the github repository since 2015, and keep updating it whenever there is a need.

* leetcode Algorithm problems
- It has been a long journey since Aug 1, 2021, since which day I began to working on my leetcode.com algroithms problems day aftter day. 
- I was first exposed to leetcode.com on April/May 2014, and solved my first about 100 problems within about 1 month。
- https://github.com/deepwaterooo/MyAlgorithms
- I began my 1st commit on end of 2014, and have been continuously working on it, and updating it, we can clearly see all the changes between years, months, and even daily. 
** Two Algorithm Summary Pdfs: which maybe valurable and good reference for Algorithm study and Summary
- https://github.com/deepwaterooo/androidPractice/blob/master/readmeFull.pdf
- https://github.com/deepwaterooo/androidPractice/blob/master/readme.pdf
- These two files could be good Algorithm reference files that I summarized, and easy to search and review. They could be downloaded without any problems. 

* Android 
- Exposure: 1st Android app project: https://github.com/deepwaterooo/AndroidAppProgramming Fall 2014, course project. 
- Now the majority of my repositories are Android base projects.  

* latex
- latex was 1st introduced to us classmeates in Spring 2013 during a course by the course instructor. 
- As a 2nd semester Computer Scienced major, I dared NOT yet and had NOT tried such a tool for a while, for about half an year. 
- but later that year during Fall 2013 when a classmate helped introduced me the Emacs org-mode of conveniently making notes, I could not help diving into it, and configure my emacs for org-mode, latex etc. 
- I have to say it has been a long journey for me to understand different font, and how font works for latex and for different OS. but year after year, eventually I am able to configure my emacs for good latex pdf layout for both Chinese and English, which I like a lot during my Algorithm practice for helping me making summary notes. 
- There could be way more pdf summarized files from https://github.com/deepwaterooo/AndroidAppDevelopmentStudy repository, but I don't bother to upload to github any more as on github, the web layout for my emacs org file summaries are very comfortable and convenient to read on github already. But I could have uploaded all the corresponding .pdf files as well. 











